### ISSUE TITLE
Bottom pagination bar does not span width of monitor

### ISSUE THREAD

**Issue by Epictek** [FreesideHull/hullblogs.com#3]
**Describe the bug**
Bottom pagination bar does not span width of monitor, should either make white span the whole monitor or remove the white background.

**To Reproduce**
on 1080p+ display scroll to bottom

**Screenshots**
https://cdn.discordapp.com/attachments/874009530122502195/878390337536679956/unknown.png

**Desktop (please complete the following information):**
Firefox Windows 10

**Comment by sbrl** [comment]
Closing due to misunderstanding
