### ISSUE TITLE
[blog request] Matt Clark 

### ISSUE THREAD

**Issue by CrimsonTome** [FreesideHull/hullblogs.com#6]
- **Link to my blog:** https://crimsontome.github.io/
 - **Link to my blog's Atom / RSS feed:** https://crimsontome.github.io/feed.xml
 - **My name as I want it to be credited:** Matt Clark

 - **I confirm that the avatar of the GitHub account I'm opening this request with is the one I want to be shown next to my name on hullblogs.com:** YES
 - **I confirm that I am a current or past University of Hull student:** YES
 - **I confirm that no content on my blog breaks any University of Hull rules:** YES

**Comment by sbrl** [comment]
Looks like this was added in 48d1f262, so I'll close this for now :-)
